# Generated by Django 3.1.2 on 2020-12-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Page', '0004_auto_20201202_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='home_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='home_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='home_uz',
            field=models.TextField(null=True),
        ),
    ]
